<?php

namespace ContainerXX7cxIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscoverProfitShareCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DiscoverProfitShareCommand' shared autowired service.
     *
     * @return \App\Command\DiscoverProfitShareCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DiscoverProfitShareCommand.php';

        $container->privates['App\\Command\\DiscoverProfitShareCommand'] = $instance = new \App\Command\DiscoverProfitShareCommand(($container->privates['App\\Service\\ProfitShareService'] ?? $container->load('getProfitShareServiceService')));

        $instance->setName('app:discover-profitshare');
        $instance->setDescription('Discover ProfitShare advertisers and their product categories');

        return $instance;
    }
}
