<?php

namespace ContainerXX7cxIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllercompareCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rq1PEF6.App\Controller\ReviewController::compareCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rq1PEF6.App\\Controller\\ReviewController::compareCategory()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]))->withContext('App\\Controller\\ReviewController::compareCategory()', $container);
    }
}
