<?php

namespace ContainerXX7cxIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeEmagCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapeEmagCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapeEmagCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-emag', [], 'Scrapes products from eMAG via ProfitShare API (Phones, Tablets, Laptops)', false, #[\Closure(name: 'App\\Command\\ScrapeEmagCommand')] fn (): \App\Command\ScrapeEmagCommand => ($container->privates['App\\Command\\ScrapeEmagCommand'] ?? $container->load('getScrapeEmagCommandService')));
    }
}
