<?php

namespace ContainerXX7cxIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeAlleopCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeAlleopCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeAlleopCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeAlleopCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->privates['App\\Command\\ScrapeAlleopCommand'] = $instance = new \App\Command\ScrapeAlleopCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')), ($container->privates['App\\Service\\HtmlSanitizerService'] ?? $container->load('getHtmlSanitizerServiceService')));

        $instance->setName('app:scrape-alleop');
        $instance->setDescription('Scrape products from Alleop.bg using Panther + Chromium');

        return $instance;
    }
}
