<?php

namespace ContainerXX7cxIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestApiCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestApiCommand' shared autowired service.
     *
     * @return \App\Command\TestApiCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestApiCommand.php';

        $container->privates['App\\Command\\TestApiCommand'] = $instance = new \App\Command\TestApiCommand($container->getEnv('PROFITSHARE_USER'), $container->getEnv('PROFITSHARE_KEY'));

        $instance->setName('app:test-api');
        $instance->setDescription('Debug ProfitShare API connection using raw CURL');

        return $instance;
    }
}
