<?php

namespace ContainerXX7cxIK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestAffiliateLinkCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestAffiliateLinkCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TestAffiliateLinkCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:test-affiliate-link', [], 'Test ProfitShare API affiliate link generation', false, #[\Closure(name: 'App\\Command\\TestAffiliateLinkCommand')] fn (): \App\Command\TestAffiliateLinkCommand => ($container->privates['App\\Command\\TestAffiliateLinkCommand'] ?? $container->load('getTestAffiliateLinkCommandService')));
    }
}
