<?php

namespace Container3Ys3R8U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rq1PEF6.App\Controller\ReviewController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rq1PEF6.App\\Controller\\ReviewController::show()'] = ($container->privates['.service_locator.rq1PEF6'] ?? $container->load('get_ServiceLocator_Rq1PEF6Service'))->withContext('App\\Controller\\ReviewController::show()', $container);
    }
}
