<?php

namespace Container3Ys3R8U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedirect404SubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\Redirect404Subscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\Redirect404Subscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/Redirect404Subscriber.php';

        return $container->privates['App\\EventSubscriber\\Redirect404Subscriber'] = new \App\EventSubscriber\Redirect404Subscriber(($container->services['router'] ?? self::getRouterService($container)));
    }
}
