<?php

namespace Container3Ys3R8U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookControllerprofitshareWebhookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..TL8LKF.App\Controller\WebhookController::profitshareWebhook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..TL8LKF.App\\Controller\\WebhookController::profitshareWebhook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'logger' => '?',
        ]))->withContext('App\\Controller\\WebhookController::profitshareWebhook()', $container);
    }
}
