<?php

namespace ContainerD7B0DGt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeAlleopCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapeAlleopCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapeAlleopCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-alleop', [], 'Scrape products from Alleop.bg using Panther + Chromium', false, #[\Closure(name: 'App\\Command\\ScrapeAlleopCommand')] fn (): \App\Command\ScrapeAlleopCommand => ($container->privates['App\\Command\\ScrapeAlleopCommand'] ?? $container->load('getScrapeAlleopCommandService')));
    }
}
