<?php

namespace ContainerD7B0DGt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateCategoriesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateCategoriesCommand' shared autowired service.
     *
     * @return \App\Command\UpdateCategoriesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UpdateCategoriesCommand.php';

        $container->privates['App\\Command\\UpdateCategoriesCommand'] = $instance = new \App\Command\UpdateCategoriesCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setName('app:update-categories');
        $instance->setDescription('Update category field for all existing products');

        return $instance;
    }
}
