<?php

namespace ContainerD7B0DGt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WebhookController' shared autowired service.
     *
     * @return \App\Controller\WebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/WebhookController.php';

        $container->services['App\\Controller\\WebhookController'] = $instance = new \App\Controller\WebhookController();

        $instance->setContainer(($container->privates['.service_locator.DweWeAE'] ?? $container->load('get_ServiceLocator_DweWeAEService'))->withContext('App\\Controller\\WebhookController', $container));

        return $instance;
    }
}
