<?php

namespace ContainerOnEqo0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompareControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CompareController' shared autowired service.
     *
     * @return \App\Controller\CompareController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CompareController.php';

        $container->services['App\\Controller\\CompareController'] = $instance = new \App\Controller\CompareController();

        $instance->setContainer(($container->privates['.service_locator.DweWeAE'] ?? $container->load('get_ServiceLocator_DweWeAEService'))->withContext('App\\Controller\\CompareController', $container));

        return $instance;
    }
}
