<?php

namespace ContainerMi9l1LS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSitemapCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateSitemapCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateSitemapCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-sitemap', [], 'Generate sitemap.xml for all published reviews', false, #[\Closure(name: 'App\\Command\\GenerateSitemapCommand')] fn (): \App\Command\GenerateSitemapCommand => ($container->privates['App\\Command\\GenerateSitemapCommand'] ?? $container->load('getGenerateSitemapCommandService')));
    }
}
