<?php

namespace ContainerMi9l1LS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSitemapCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateSitemapCommand' shared autowired service.
     *
     * @return \App\Command\GenerateSitemapCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateSitemapCommand.php';

        $container->privates['App\\Command\\GenerateSitemapCommand'] = $instance = new \App\Command\GenerateSitemapCommand(($container->privates['App\\Repository\\ReviewRepository'] ?? $container->load('getReviewRepositoryService')), ($container->services['router'] ?? self::getRouterService($container)), \dirname(__DIR__, 4));

        $instance->setName('app:generate-sitemap');
        $instance->setDescription('Generate sitemap.xml for all published reviews');

        return $instance;
    }
}
