<?php

namespace ContainerMi9l1LS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllerbuyRedirectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T6qA044.App\Controller\ReviewController::buyRedirect()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T6qA044.App\\Controller\\ReviewController::buyRedirect()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'profitShareService' => ['privates', 'App\\Service\\ProfitShareService', 'getProfitShareServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
            'profitShareService' => 'App\\Service\\ProfitShareService',
            'logger' => '?',
        ]))->withContext('App\\Controller\\ReviewController::buyRedirect()', $container);
    }
}
