<?php

namespace ContainerMi9l1LS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iVeQ29l.App\Controller\ReviewController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.iVeQ29l'] ?? $container->load('get_ServiceLocator_IVeQ29lService'));

        if (isset($container->privates['.service_locator.iVeQ29l.App\\Controller\\ReviewController::index()'])) {
            return $container->privates['.service_locator.iVeQ29l.App\\Controller\\ReviewController::index()'];
        }

        return $container->privates['.service_locator.iVeQ29l.App\\Controller\\ReviewController::index()'] = $a->withContext('App\\Controller\\ReviewController::index()', $container);
    }
}
