<?php

namespace ContainerMi9l1LS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeProductCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeProductCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeProductCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeProductCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->privates['App\\Command\\ScrapeProductCommand'] = $instance = new \App\Command\ScrapeProductCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')));

        $instance->setName('app:scrape-product');
        $instance->setDescription('Скрейпва продукт от eMAG и създава подробно ревю тип Wirecutter');

        return $instance;
    }
}
