<?php

namespace ContainerA8tUTh7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddProductCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\AddProductCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\AddProductCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:add-product', [], 'Manually add a product to the site (Great for eMAG)', false, #[\Closure(name: 'App\\Command\\AddProductCommand')] fn (): \App\Command\AddProductCommand => ($container->privates['App\\Command\\AddProductCommand'] ?? $container->load('getAddProductCommandService')));
    }
}
