<?php

namespace ContainerA8tUTh7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllercomparePricesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rq1PEF6.App\Controller\ReviewController::comparePrices()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rq1PEF6.App\\Controller\\ReviewController::comparePrices()'] = ($container->privates['.service_locator.rq1PEF6'] ?? $container->load('get_ServiceLocator_Rq1PEF6Service'))->withContext('App\\Controller\\ReviewController::comparePrices()', $container);
    }
}
