<?php

namespace ContainerFxe5zlh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateLinkCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateLinkCommand' shared autowired service.
     *
     * @return \App\Command\GenerateLinkCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateLinkCommand.php';

        $container->privates['App\\Command\\GenerateLinkCommand'] = $instance = new \App\Command\GenerateLinkCommand(($container->privates['App\\Service\\ProfitShareService'] ?? $container->load('getProfitShareServiceService')));

        $instance->setName('app:link');
        $instance->setDescription('Generates an affiliate link for any eMAG product');

        return $instance;
    }
}
