<?php

namespace ContainerFxe5zlh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfitShareServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProfitShareService' shared autowired service.
     *
     * @return \App\Service\ProfitShareService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ProfitShareService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ProfitShareService'])) {
            return $container->privates['App\\Service\\ProfitShareService'];
        }

        return $container->privates['App\\Service\\ProfitShareService'] = new \App\Service\ProfitShareService($container->getEnv('PROFITSHARE_USER'), $container->getEnv('PROFITSHARE_KEY'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $a, ($container->privates['App\\Repository\\AffiliateLinkRepository'] ?? $container->load('getAffiliateLinkRepositoryService')));
    }
}
