<?php

namespace ContainerFxe5zlh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuickScrapeCampaignCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\QuickScrapeCampaignCommand' shared autowired service.
     *
     * @return \App\Command\QuickScrapeCampaignCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/QuickScrapeCampaignCommand.php';

        $container->privates['App\\Command\\QuickScrapeCampaignCommand'] = $instance = new \App\Command\QuickScrapeCampaignCommand(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:quick-scrape');
        $instance->setDescription('🚀 FAST: Scrape eMag campaign using data attributes');

        return $instance;
    }
}
