<?php

namespace ContainerFxe5zlh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeFashionDaysCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeFashionDaysCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeFashionDaysCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeFashionDaysCommand.php';

        $container->privates['App\\Command\\ScrapeFashionDaysCommand'] = $instance = new \App\Command\ScrapeFashionDaysCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:scrape-fashion');
        $instance->setDescription('Scrapes FashionDays (Final Fix with Link Cleaner)');

        return $instance;
    }
}
