<?php

namespace ContainerGVaxtZl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeCampaignCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapeCampaignCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapeCampaignCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-campaign', [], '🔥 Scrape entire eMag campaign pages (1-5) and generate reviews with affiliate links', false, #[\Closure(name: 'App\\Command\\ScrapeCampaignCommand')] fn (): \App\Command\ScrapeCampaignCommand => ($container->privates['App\\Command\\ScrapeCampaignCommand'] ?? $container->load('getScrapeCampaignCommandService')));
    }
}
