<?php

namespace ContainerGVaxtZl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeCampaignCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeCampaignCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeCampaignCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeCampaignCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/EmagScraper.php';

        $a = ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'));

        $container->privates['App\\Command\\ScrapeCampaignCommand'] = $instance = new \App\Command\ScrapeCampaignCommand($a, new \App\Service\EmagScraper($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:scrape-campaign');
        $instance->setDescription('🔥 Scrape entire eMag campaign pages (1-5) and generate reviews with affiliate links');

        return $instance;
    }
}
