<?php

namespace ContainerGVaxtZl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeFashionDaysCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapeFashionDaysCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapeFashionDaysCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-fashion', [], 'Scrapes FashionDays (Final Fix with Link Cleaner)', false, #[\Closure(name: 'App\\Command\\ScrapeFashionDaysCommand')] fn (): \App\Command\ScrapeFashionDaysCommand => ($container->privates['App\\Command\\ScrapeFashionDaysCommand'] ?? $container->load('getScrapeFashionDaysCommandService')));
    }
}
