<?php

namespace ContainerYJC3GUB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VtXAS0mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VtXAS0m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VtXAS0m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ReviewController::index' => ['privates', '.service_locator.rankbLT.App\\Controller\\ReviewController::index()', 'getReviewControllerindexService', true],
            'App\\Controller\\ReviewController::showCategory' => ['privates', '.service_locator.77H4LMt.App\\Controller\\ReviewController::showCategory()', 'getReviewControllershowCategoryService', true],
            'App\\Controller\\ReviewController::show' => ['privates', '.service_locator.O6NwTWa.App\\Controller\\ReviewController::show()', 'getReviewControllershowService', true],
            'App\\Controller\\ReviewController::search' => ['privates', '.service_locator.iVeQ29l.App\\Controller\\ReviewController::search()', 'getReviewControllersearchService', true],
            'App\\Controller\\ReviewController::comparePrices' => ['privates', '.service_locator.O6NwTWa.App\\Controller\\ReviewController::comparePrices()', 'getReviewControllercomparePricesService', true],
            'App\\Controller\\ReviewController::recommendations' => ['privates', '.service_locator.O6NwTWa.App\\Controller\\ReviewController::recommendations()', 'getReviewControllerrecommendationsService', true],
            'App\\Controller\\ReviewController::compareCategory' => ['privates', '.service_locator.rq1PEF6.App\\Controller\\ReviewController::compareCategory()', 'getReviewControllercompareCategoryService', true],
            'App\\Controller\\ReviewController::buyRedirect' => ['privates', '.service_locator.T6qA044.App\\Controller\\ReviewController::buyRedirect()', 'getReviewControllerbuyRedirectService', true],
            'App\\Controller\\WebhookController::profitshareWebhook' => ['privates', '.service_locator..TL8LKF.App\\Controller\\WebhookController::profitshareWebhook()', 'getWebhookControllerprofitshareWebhookService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ReviewController:index' => ['privates', '.service_locator.rankbLT.App\\Controller\\ReviewController::index()', 'getReviewControllerindexService', true],
            'App\\Controller\\ReviewController:showCategory' => ['privates', '.service_locator.77H4LMt.App\\Controller\\ReviewController::showCategory()', 'getReviewControllershowCategoryService', true],
            'App\\Controller\\ReviewController:show' => ['privates', '.service_locator.O6NwTWa.App\\Controller\\ReviewController::show()', 'getReviewControllershowService', true],
            'App\\Controller\\ReviewController:search' => ['privates', '.service_locator.iVeQ29l.App\\Controller\\ReviewController::search()', 'getReviewControllersearchService', true],
            'App\\Controller\\ReviewController:comparePrices' => ['privates', '.service_locator.O6NwTWa.App\\Controller\\ReviewController::comparePrices()', 'getReviewControllercomparePricesService', true],
            'App\\Controller\\ReviewController:recommendations' => ['privates', '.service_locator.O6NwTWa.App\\Controller\\ReviewController::recommendations()', 'getReviewControllerrecommendationsService', true],
            'App\\Controller\\ReviewController:compareCategory' => ['privates', '.service_locator.rq1PEF6.App\\Controller\\ReviewController::compareCategory()', 'getReviewControllercompareCategoryService', true],
            'App\\Controller\\ReviewController:buyRedirect' => ['privates', '.service_locator.T6qA044.App\\Controller\\ReviewController::buyRedirect()', 'getReviewControllerbuyRedirectService', true],
            'App\\Controller\\WebhookController:profitshareWebhook' => ['privates', '.service_locator..TL8LKF.App\\Controller\\WebhookController::profitshareWebhook()', 'getWebhookControllerprofitshareWebhookService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ReviewController::index' => '?',
            'App\\Controller\\ReviewController::showCategory' => '?',
            'App\\Controller\\ReviewController::show' => '?',
            'App\\Controller\\ReviewController::search' => '?',
            'App\\Controller\\ReviewController::comparePrices' => '?',
            'App\\Controller\\ReviewController::recommendations' => '?',
            'App\\Controller\\ReviewController::compareCategory' => '?',
            'App\\Controller\\ReviewController::buyRedirect' => '?',
            'App\\Controller\\WebhookController::profitshareWebhook' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ReviewController:index' => '?',
            'App\\Controller\\ReviewController:showCategory' => '?',
            'App\\Controller\\ReviewController:show' => '?',
            'App\\Controller\\ReviewController:search' => '?',
            'App\\Controller\\ReviewController:comparePrices' => '?',
            'App\\Controller\\ReviewController:recommendations' => '?',
            'App\\Controller\\ReviewController:compareCategory' => '?',
            'App\\Controller\\ReviewController:buyRedirect' => '?',
            'App\\Controller\\WebhookController:profitshareWebhook' => '?',
        ]);
    }
}
