<?php

namespace ContainerYJC3GUB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryMappingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CategoryMappingService' shared autowired service.
     *
     * @return \App\Service\CategoryMappingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CategoryMappingService.php';

        return $container->privates['App\\Service\\CategoryMappingService'] = new \App\Service\CategoryMappingService(($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
