<?php

namespace ContainerYJC3GUB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllershowCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.77H4LMt.App\Controller\ReviewController::showCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.77H4LMt.App\\Controller\\ReviewController::showCategory()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ReviewController::showCategory()', $container);
    }
}
