<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIjGxr6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIjGxr6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIjGxr6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIjGxr6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIjGxr6\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIjGxr6',
    'container.build_id' => 'd700c078',
    'container.build_time' => 1766596713,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIjGxr6');
