<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMi9l1LS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMi9l1LS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMi9l1LS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMi9l1LS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMi9l1LS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mi9l1LS',
    'container.build_id' => 'cca7b450',
    'container.build_time' => 1766129228,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMi9l1LS');
