<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA8tUTh7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA8tUTh7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA8tUTh7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA8tUTh7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA8tUTh7\App_KernelDevDebugContainer([
    'container.build_hash' => 'A8tUTh7',
    'container.build_id' => '10e01bc5',
    'container.build_time' => 1766154748,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA8tUTh7');
