<?php

namespace ContainerJSS84Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateCategoriesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MigrateCategoriesCommand' shared autowired service.
     *
     * @return \App\Command\MigrateCategoriesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/MigrateCategoriesCommand.php';

        $container->privates['App\\Command\\MigrateCategoriesCommand'] = $instance = new \App\Command\MigrateCategoriesCommand(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Service\\CategoryMappingService'] ?? $container->load('getCategoryMappingServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:migrate-categories');
        $instance->setDescription('Migrate existing products to use the new Category system');

        return $instance;
    }
}
