<?php

namespace ContainerJSS84Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeEmagCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeEmagCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeEmagCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeEmagCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->privates['App\\Command\\ScrapeEmagCommand'] = $instance = new \App\Command\ScrapeEmagCommand(($container->privates['App\\Service\\ProfitShareService'] ?? $container->load('getProfitShareServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Repository\\ReviewRepository'] ?? $container->load('getReviewRepositoryService')), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')), ($container->privates['App\\Service\\CategoryMappingService'] ?? $container->load('getCategoryMappingServiceService')));

        $instance->setName('app:scrape-emag');
        $instance->setDescription('Scrapes products from eMAG via ProfitShare API (Phones, Tablets, Laptops)');

        return $instance;
    }
}
