<?php

namespace ContainerSIjGxr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateLinkCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateLinkCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateLinkCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:link', [], 'Generates an affiliate link for any eMAG product', false, #[\Closure(name: 'App\\Command\\GenerateLinkCommand')] fn (): \App\Command\GenerateLinkCommand => ($container->privates['App\\Command\\GenerateLinkCommand'] ?? $container->load('getGenerateLinkCommandService')));
    }
}
