<?php

namespace ContainerSIjGxr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlSanitizerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HtmlSanitizerService' shared autowired service.
     *
     * @return \App\Service\HtmlSanitizerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/HtmlSanitizerService.php';

        return $container->privates['App\\Service\\HtmlSanitizerService'] = new \App\Service\HtmlSanitizerService(($container->privates['html_sanitizer.sanitizer.default'] ?? $container->load('getHtmlSanitizer_Sanitizer_DefaultService')));
    }
}
