<?php

namespace ContainerSIjGxr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateCategoriesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\MigrateCategoriesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\MigrateCategoriesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:migrate-categories', [], 'Migrate existing products to use the new Category system', false, #[\Closure(name: 'App\\Command\\MigrateCategoriesCommand')] fn (): \App\Command\MigrateCategoriesCommand => ($container->privates['App\\Command\\MigrateCategoriesCommand'] ?? $container->load('getMigrateCategoriesCommandService')));
    }
}
