<?php

namespace ContainerSIjGxr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestAffiliateLinkCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestAffiliateLinkCommand' shared autowired service.
     *
     * @return \App\Command\TestAffiliateLinkCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestAffiliateLinkCommand.php';

        $container->privates['App\\Command\\TestAffiliateLinkCommand'] = $instance = new \App\Command\TestAffiliateLinkCommand(($container->privates['App\\Service\\ProfitShareService'] ?? $container->load('getProfitShareServiceService')));

        $instance->setName('app:test-affiliate-link');
        $instance->setDescription('Test ProfitShare API affiliate link generation');

        return $instance;
    }
}
