<?php

namespace ContainerSIjGxr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateCategoriesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\UpdateCategoriesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\UpdateCategoriesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-categories', [], 'Update category field for all existing products', false, #[\Closure(name: 'App\\Command\\UpdateCategoriesCommand')] fn (): \App\Command\UpdateCategoriesCommand => ($container->privates['App\\Command\\UpdateCategoriesCommand'] ?? $container->load('getUpdateCategoriesCommandService')));
    }
}
