<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LXjQiaaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LXjQiaa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LXjQiaa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ReviewController::index' => ['privates', '.service_locator.18a9E3e.App\\Controller\\ReviewController::index()', 'getReviewControllerindexService', true],
            'App\\Controller\\ReviewController::show' => ['privates', '.service_locator.mMnVkcL.App\\Controller\\ReviewController::show()', 'getReviewControllershowService', true],
            'App\\Controller\\ReviewController::search' => ['privates', '.service_locator.iVeQ29l.App\\Controller\\ReviewController::search()', 'getReviewControllersearchService', true],
            'App\\Controller\\ReviewController::buyRedirect' => ['privates', '.service_locator.T6qA044.App\\Controller\\ReviewController::buyRedirect()', 'getReviewControllerbuyRedirectService', true],
            'App\\Controller\\ReviewController::comparePrices' => ['privates', '.service_locator.mMnVkcL.App\\Controller\\ReviewController::comparePrices()', 'getReviewControllercomparePricesService', true],
            'App\\Controller\\ReviewController::compareProduct' => ['privates', '.service_locator.mMnVkcL.App\\Controller\\ReviewController::compareProduct()', 'getReviewControllercompareProductService', true],
            'App\\Controller\\WebhookController::profitshareWebhook' => ['privates', '.service_locator..TL8LKF.App\\Controller\\WebhookController::profitshareWebhook()', 'getWebhookControllerprofitshareWebhookService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ReviewController:index' => ['privates', '.service_locator.18a9E3e.App\\Controller\\ReviewController::index()', 'getReviewControllerindexService', true],
            'App\\Controller\\ReviewController:show' => ['privates', '.service_locator.mMnVkcL.App\\Controller\\ReviewController::show()', 'getReviewControllershowService', true],
            'App\\Controller\\ReviewController:search' => ['privates', '.service_locator.iVeQ29l.App\\Controller\\ReviewController::search()', 'getReviewControllersearchService', true],
            'App\\Controller\\ReviewController:buyRedirect' => ['privates', '.service_locator.T6qA044.App\\Controller\\ReviewController::buyRedirect()', 'getReviewControllerbuyRedirectService', true],
            'App\\Controller\\ReviewController:comparePrices' => ['privates', '.service_locator.mMnVkcL.App\\Controller\\ReviewController::comparePrices()', 'getReviewControllercomparePricesService', true],
            'App\\Controller\\ReviewController:compareProduct' => ['privates', '.service_locator.mMnVkcL.App\\Controller\\ReviewController::compareProduct()', 'getReviewControllercompareProductService', true],
            'App\\Controller\\WebhookController:profitshareWebhook' => ['privates', '.service_locator..TL8LKF.App\\Controller\\WebhookController::profitshareWebhook()', 'getWebhookControllerprofitshareWebhookService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ReviewController::index' => '?',
            'App\\Controller\\ReviewController::show' => '?',
            'App\\Controller\\ReviewController::search' => '?',
            'App\\Controller\\ReviewController::buyRedirect' => '?',
            'App\\Controller\\ReviewController::comparePrices' => '?',
            'App\\Controller\\ReviewController::compareProduct' => '?',
            'App\\Controller\\WebhookController::profitshareWebhook' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ReviewController:index' => '?',
            'App\\Controller\\ReviewController:show' => '?',
            'App\\Controller\\ReviewController:search' => '?',
            'App\\Controller\\ReviewController:buyRedirect' => '?',
            'App\\Controller\\ReviewController:comparePrices' => '?',
            'App\\Controller\\ReviewController:compareProduct' => '?',
            'App\\Controller\\WebhookController:profitshareWebhook' => '?',
        ]);
    }
}
