<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuickScrapeCampaignCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\QuickScrapeCampaignCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\QuickScrapeCampaignCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:quick-scrape', [], '🚀 FAST: Scrape eMag campaign using data attributes', false, #[\Closure(name: 'App\\Command\\QuickScrapeCampaignCommand')] fn (): \App\Command\QuickScrapeCampaignCommand => ($container->privates['App\\Command\\QuickScrapeCampaignCommand'] ?? $container->load('getQuickScrapeCampaignCommandService')));
    }
}
