<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iVeQ29l.App\Controller\ReviewController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iVeQ29l.App\\Controller\\ReviewController::search()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ReviewController::search()', $container);
    }
}
