<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeEmagHtmlCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapeEmagHtmlCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapeEmagHtmlCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-html', [], 'Универсален скрейпър за eMAG, FashionDays и Alleop (SQL версия)', false, #[\Closure(name: 'App\\Command\\ScrapeEmagHtmlCommand')] fn (): \App\Command\ScrapeEmagHtmlCommand => ($container->privates['App\\Command\\ScrapeEmagHtmlCommand'] ?? $container->load('getScrapeEmagHtmlCommandService')));
    }
}
