<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeEmagHtmlCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeEmagHtmlCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeEmagHtmlCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeEmagHtmlCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->privates['App\\Command\\ScrapeEmagHtmlCommand'] = $instance = new \App\Command\ScrapeEmagHtmlCommand(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['App\\Service\\ProfitShareService'] ?? $container->load('getProfitShareServiceService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')), ($container->privates['App\\Service\\HtmlSanitizerService'] ?? $container->load('getHtmlSanitizerServiceService')));

        $instance->setName('app:scrape-html');
        $instance->setDescription('Универсален скрейпър за eMAG, FashionDays и Alleop (SQL версия)');

        return $instance;
    }
}
