<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestConnectionCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestConnectionCommand' shared autowired service.
     *
     * @return \App\Command\TestConnectionCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestConnectionCommand.php';

        $container->privates['App\\Command\\TestConnectionCommand'] = $instance = new \App\Command\TestConnectionCommand(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setName('app:test-connection');
        $instance->setDescription('Debug Docker environment and ProfitShare API connection');

        return $instance;
    }
}
