<?php

namespace ContainerHy5oiJW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestApiCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestApiCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TestApiCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:test-api', [], 'Debug ProfitShare API connection using raw CURL', false, #[\Closure(name: 'App\\Command\\TestApiCommand')] fn (): \App\Command\TestApiCommand => ($container->privates['App\\Command\\TestApiCommand'] ?? $container->load('getTestApiCommandService')));
    }
}
